/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Record({
  'id' : IDL.Text,
  'postCount' : IDL.Nat,
  'name' : IDL.Text,
});
export const Time = IDL.Int;
export const BlogPost = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'authorAvatar' : IDL.Text,
  'date' : Time,
  'tags' : IDL.Vec(IDL.Text),
  'author' : IDL.Text,
  'imageUrl' : IDL.Text,
  'viewCount' : IDL.Nat,
  'excerpt' : IDL.Text,
  'commentCount' : IDL.Nat,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getPost' : IDL.Func([IDL.Text], [BlogPost], ['query']),
  'getPosts' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
      [IDL.Record({ 'total' : IDL.Nat, 'posts' : IDL.Vec(BlogPost) })],
      [],
    ),
  'getRecentPosts' : IDL.Func([IDL.Nat], [IDL.Vec(BlogPost)], ['query']),
  'getTags' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'searchSuggestions' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Record({
    'id' : IDL.Text,
    'postCount' : IDL.Nat,
    'name' : IDL.Text,
  });
  const Time = IDL.Int;
  const BlogPost = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'authorAvatar' : IDL.Text,
    'date' : Time,
    'tags' : IDL.Vec(IDL.Text),
    'author' : IDL.Text,
    'imageUrl' : IDL.Text,
    'viewCount' : IDL.Nat,
    'excerpt' : IDL.Text,
    'commentCount' : IDL.Nat,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getPost' : IDL.Func([IDL.Text], [BlogPost], ['query']),
    'getPosts' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
        [IDL.Record({ 'total' : IDL.Nat, 'posts' : IDL.Vec(BlogPost) })],
        [],
      ),
    'getRecentPosts' : IDL.Func([IDL.Nat], [IDL.Vec(BlogPost)], ['query']),
    'getTags' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'searchSuggestions' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };